[options]
# How often to run checks in minutes
interval = 3
# Verbose logging. true or false
verbose = false

[telegram]
# Telegram bot API key
api = ""
# Chat to post to, usually a negative number for groups and a positive one for direct
chat = ""