# Options for Gogios
# https://github.com/bkasin/gogios
# https://angrysysadmins.tech


[options]
  # How often to run checks in minutes
  interval = "3m"
  # Verbose logging. true or false
  verbose = false

  # Per checkout timeout in seconds
  # If enough checks get stuck it is possible that the
  # next round will start before the previous finishes
  timeout = "60s"


[web_options]
  # Change IP to 0.0.0.0 to listen on all interfaces
  IP = "127.0.0.1"
  http_port = 8411
  https_port = 8412

  # Should the website be hosted on HTTPS
  SSL = false
  # Redirect from HTTP to HTTPS
  redirect = false

  # Path to TLS cert and key for HTTPS
  tls_cert = ""
  tls_key = ""

  expose_api = true
  api_ip = "0.0.0.0"
  api_port = 8413


###########################
#
# Notifiers
#
###########################


# # Send a notification to a Slack channel using a bot when a check changes states
# [[notifiers.slack]]
#   ## Slack bot API token
#   token = ""
#   ## Channel ID to post message to
#   chats = ""


# # Send a notification to a Telegram channel using a bot when a check changes states
# [[notifiers.telegram]]
#   ## Telegram bot API key
#   api = ""
#   ## Chat to post to, usually a negative number for groups and a positive one for direct
#   chats = [""]
#
#   ## HTTP response timeout (default: 10s)
#   response_timeout = "10s"


# # Send a text message to a phone number using Twilio's REST API
# [[notifiers.twilio]]
#   ## Account SID
#   sid = ""
#   ## Account auth token
#   token = ""
#   ## Phone number for your Twilio account
#   twilio_number = ""
#   ## Phone number that should be texted with the notification
#   send_to = ""
#
#   ## HTTP response timeout (default: 10s)
#   response_timeout = "10s"

